name: core_plugin
description: A new Flutter package.
version: 0.4.2+00402
author: TungPham <phamthanhtung1995@gmail.com>
homepage: https://tungpt.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  url_launcher: ^5.4.10

  # dio, http request
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  dio_http2_adapter: ^1.0.0
  dio_http_cache: ^0.2.7
  retrofit: ^1.3.4

  logger: ^0.9.1
  equatable: ^1.2.0

  # bloc, state management
  flutter_bloc: ^4.0.0
  bloc_test: ^5.1.0

  rxdart: ^0.24.1

  # json serializable
  json_annotation: ^3.0.1

  shared_preferences: ^0.5.7+3
  cupertino_icons: ^0.1.3

  flutter_widgets: ^0.1.12
  path_provider: ^1.6.10
  toast: 0.1.5
  permission_handler: ^5.0.1
  sticky_headers: ^0.1.8+1
  image_picker: ^0.6.7+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/error.png
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
